In [2]:
import pandas as pd

In [34]:
popdf = pd.read_csv("pop_data.csv", delimiter=",",index_col=0)

In [35]:
popdf.head()

,Country_Code,YR1986,YR1987,YR1988,YR1989,YR1990,YR1991,YR1992,YR1993,YR1994,...,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022
0,AT,7569794.0,7574586.0,7585317.0,7619567.0,7677850.0,7754891.0,7840709.0,7905633.0,7936118.0,...,8479823.0,8546356.0,8642699.0,8736668.0,8797566.0,8840521.0,8879920.0,8916864.0,8955797.0,9042528.0
1,BE,9861823.0,9870234.0,9901664.0,9937697.0,9967379.0,10004486.0,10045158.0,10084475.0,10115603.0,...,11159407.0,11209057.0,11274196.0,11331422.0,11375158.0,11427054.0,11488980.0,11538604.0,11592952.0,11669446.0
2,BG,8958171.0,8971359.0,8981446.0,8876972.0,8718289.0,8632367.0,8540164.0,8472313.0,8443591.0,...,7265115.0,7223938.0,7177991.0,7127822.0,7075947.0,7025037.0,6975761.0,6934015.0,6877743.0,6465097.0
3,CY,743446.0,755021.0,766412.0,777592.0,788500.0,799061.0,810431.0,825986.0,844444.0,...,1166968.0,1176995.0,1187280.0,1197881.0,1208523.0,1218831.0,1228836.0,1237537.0,1244188.0,1251488.0
4,CZ,10342227.0,10347318.0,10355276.0,10361068.0,10333355.0,10308578.0,10319123.0,10329855.0,10333587.0,...,10514272.0,10525347.0,10546059.0,10566332.0,10594438.0,10629928.0,10671870.0,10697858.0,10505772.0,10526073.0

In [54]:
EUList_alpha2 = ['BE', 'BG', 'CZ', 'DK', 'DE', 'EE', 'IE', 'EL', 'ES', 'FR', 'HR', 'IT', 'CY', 'LV', 'LT', 'LU', 'HU', 'MT', 'NL', 'AT', 'PL', 'PT', 'RO', 'SI', 'SK', 'FI', 'SE']
Dict = {}
for country in EUList_alpha2:
    #print(country)
    Dict[country] = popdf.loc[popdf['Country_Code'] == country]

In [57]:
print(Dict)

  Country_Code     YR1986     YR1987     YR1988     YR1989     YR1990  \
1           BE  9861823.0  9870234.0  9901664.0  9937697.0  9967379.0

       YR1991      YR1992      YR1993      YR1994  ...      YR2013  \
1  10004486.0  10045158.0  10084475.0  10115603.0  ...  11159407.0

       YR2014      YR2015      YR2016      YR2017      YR2018      YR2019  \
1  11209057.0  11274196.0  11331422.0  11375158.0  11427054.0  11488980.0

       YR2020      YR2021      YR2022
1  11538604.0  11592952.0  11669446.0

[1 rows x 38 columns]