In [34]:
import pandas as pd
import numpy as np

In [45]:
tempdf = pd.read_csv("TemperatureData.csv", delimiter=",")
tempsel = tempdf.loc[tempdf["Date"] >= "1986-01-01"]
tempsel["Date"] = tempsel["Date"].str[:-3]

/tmp/ipykernel_14525/1502169267.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tempsel["Date"] = tempsel["Date"].str[:-3]

In [46]:

#tempsel["Date"] = pd.to_numeric(tempsel["Date"])
dates = pd.unique(tempsel["Date"])
#tempsel.loc[tempsel["Date"] == dates[300], tempsel.columns != "Date"].mean()

['1986-01' '1986-02' '1986-03' '1986-04' '1986-05' '1986-06' '1986-07'
 '1986-08' '1986-09' '1986-10' '1986-11' '1986-12' '1987-01' '1987-02'
 '1987-03' '1987-04' '1987-05' '1987-06' '1987-07' '1987-08' '1987-09'
 '1987-10' '1987-11' '1987-12' '1988-01' '1988-02' '1988-03' '1988-04'
 '1988-05' '1988-06' '1988-07' '1988-08' '1988-09' '1988-10' '1988-11'
 '1988-12' '1989-01' '1989-02' '1989-03' '1989-04' '1989-05' '1989-06'
 '1989-07' '1989-08' '1989-09' '1989-10' '1989-11' '1989-12' '1990-01'
 '1990-02' '1990-03' '1990-04' '1990-05' '1990-06' '1990-07' '1990-08'
 '1990-09' '1990-10' '1990-11' '1990-12' '1991-01' '1991-02' '1991-03'
 '1991-04' '1991-05' '1991-06' '1991-07' '1991-08' '1991-09' '1991-10'
 '1991-11' '1991-12' '1992-01' '1992-02' '1992-03' '1992-04' '1992-05'
 '1992-06' '1992-07' '1992-08' '1992-09' '1992-10' '1992-11' '1992-12'
 '1993-01' '1993-02' '1993-03' '1993-04' '1993-05' '1993-06' '1993-07'
 '1993-08' '1993-09' '1993-10' '1993-11' '1993-12' '1994-01' '1994-02'
 '1994-03' '1994-04' '1994-05' '1994-06' '1994-07' '1994-08' '1994-09'
 '1994-10' '1994-11' '1994-12' '1995-01' '1995-02' '1995-03' '1995-04'
 '1995-05' '1995-06' '1995-07' '1995-08' '1995-09' '1995-10' '1995-11'
 '1995-12' '1996-01' '1996-02' '1996-03' '1996-04' '1996-05' '1996-06'
 '1996-07' '1996-08' '1996-09' '1996-10' '1996-11' '1996-12' '1997-01'
 '1997-02' '1997-03' '1997-04' '1997-05' '1997-06' '1997-07' '1997-08'
 '1997-09' '1997-10' '1997-11' '1997-12' '1998-01' '1998-02' '1998-03'
 '1998-04' '1998-05' '1998-06' '1998-07' '1998-08' '1998-09' '1998-10'
 '1998-11' '1998-12' '1999-01' '1999-02' '1999-03' '1999-04' '1999-05'
 '1999-06' '1999-07' '1999-08' '1999-09' '1999-10' '1999-11' '1999-12'
 '2000-01' '2000-02' '2000-03' '2000-04' '2000-05' '2000-06' '2000-07'
 '2000-08' '2000-09' '2000-10' '2000-11' '2000-12' '2001-01' '2001-02'
 '2001-03' '2001-04' '2001-05' '2001-06' '2001-07' '2001-08' '2001-09'
 '2001-10' '2001-11' '2001-12' '2002-01' '2002-02' '2002-03' '2002-04'
 '2002-05' '2002-06' '2002-07' '2002-08' '2002-09' '2002-10' '2002-11'
 '2002-12' '2003-01' '2003-02' '2003-03' '2003-04' '2003-05' '2003-06'
 '2003-07' '2003-08' '2003-09' '2003-10' '2003-11' '2003-12' '2004-01'
 '2004-02' '2004-03' '2004-04' '2004-05' '2004-06' '2004-07' '2004-08'
 '2004-09' '2004-10' '2004-11' '2004-12' '2005-01' '2005-02' '2005-03'
 '2005-04' '2005-05' '2005-06' '2005-07' '2005-08' '2005-09' '2005-10'
 '2005-11' '2005-12' '2006-01' '2006-02' '2006-03' '2006-04' '2006-05'
 '2006-06' '2006-07' '2006-08' '2006-09' '2006-10' '2006-11' '2006-12'
 '2007-01' '2007-02' '2007-03' '2007-04' '2007-05' '2007-06' '2007-07'
 '2007-08' '2007-09' '2007-10' '2007-11' '2007-12' '2008-01' '2008-02'
 '2008-03' '2008-04' '2008-05' '2008-06' '2008-07' '2008-08' '2008-09'
 '2008-10' '2008-11' '2008-12' '2009-01' '2009-02' '2009-03' '2009-04'
 '2009-05' '2009-06' '2009-07' '2009-08' '2009-09' '2009-10' '2009-11'
 '2009-12' '2010-01' '2010-02' '2010-03' '2010-04' '2010-05' '2010-06'
 '2010-07' '2010-08' '2010-09' '2010-10' '2010-11' '2010-12' '2011-01'
 '2011-02' '2011-03' '2011-04' '2011-05' '2011-06' '2011-07' '2011-08'
 '2011-09' '2011-10' '2011-11' '2011-12' '2012-01' '2012-02' '2012-03'
 '2012-04' '2012-05' '2012-06' '2012-07' '2012-08' '2012-09' '2012-10'
 '2012-11' '2012-12' '2013-01' '2013-02' '2013-03' '2013-04' '2013-05'
 '2013-06' '2013-07' '2013-08' '2013-09' '2013-10' '2013-11' '2013-12'
 '2014-01' '2014-02' '2014-03' '2014-04' '2014-05' '2014-06' '2014-07'
 '2014-08' '2014-09' '2014-10' '2014-11' '2014-12' '2015-01' '2015-02'
 '2015-03' '2015-04' '2015-05' '2015-06' '2015-07' '2015-08' '2015-09'
 '2015-10' '2015-11' '2015-12' '2016-01' '2016-02' '2016-03' '2016-04'
 '2016-05' '2016-06' '2016-07' '2016-08' '2016-09' '2016-10' '2016-11'
 '2016-12' '2017-01' '2017-02' '2017-03' '2017-04' '2017-05' '2017-06'
 '2017-07' '2017-08' '2017-09' '2017-10' '2017-11' '2017-12' '2018-01'
 '2018-02' '2018-03' '2018-04' '2018-05' '2018-06' '2018-07' '2018-08'
 '2018-09' '2018-10' '2018-11' '2018-12' '2019-01' '2019-02' '2019-03'
 '2019-04' '2019-05' '2019-06' '2019-07' '2019-08' '2019-09' '2019-10'
 '2019-11' '2019-12' '2020-01' '2020-02' '2020-03' '2020-04' '2020-05'
 '2020-06' '2020-07' '2020-08' '2020-09' '2020-10' '2020-11' '2020-12'
 '2021-01' '2021-02' '2021-03' '2021-04' '2021-05' '2021-06' '2021-07'
 '2021-08' '2021-09' '2021-10' '2021-11' '2021-12' '2022-01' '2022-02'
 '2022-03' '2022-04' '2022-05' '2022-06' '2022-07' '2022-08' '2022-09'
 '2022-10' '2022-11' '2022-12' '2023-01' '2023-02' '2023-03' '2023-04'
 '2023-05' '2023-06' '2023-07' '2023-08']

In [48]:
meanlist = []
for date in dates:
    a = tempsel.loc[tempsel["Date"] == date, tempsel.columns != "Date"].mean()
    meanlist.append(a)
tempmeans = pd.DataFrame(meanlist)

In [60]:
tempdf2 = tempmeans.T
tempdf2.columns = dates
tempdf2.head()

,1986-01,1986-02,1986-03,1986-04,1986-05,1986-06,1986-07,1986-08,1986-09,1986-10,...,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08
AT,-2.354839,-6.285714,2.225806,8.033333,14.548387,15.133333,16.645161,17.483871,13.3,9.225806,...,5.166667,0.612903,1.290323,1.892857,5.903226,6.966667,12.870968,18.033333,20.096774,19.16129
BE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.866667,4.096774,5.548387,5.785714,7.580645,8.966667,14.032258,20.333333,18.612903,18.225806
HR,3.935484,0.75,6.322581,12.033333,18.290323,18.766667,20.580645,22.354839,17.233333,13.225806,...,10.466667,7.903226,6.612903,5.607143,9.548387,10.933333,16.483871,19.7,24.516129,23.451613
CY,11.580645,12.321429,14.064516,18.7,19.451613,24.8,26.483871,26.935484,25.8,19.806452,...,18.913043,16.258065,14.419355,11.857143,15.903226,17.7,21.387097,24.233333,28.83871,28.483871
DK,-0.483871,-4.142857,1.677419,4.233333,11.193548,14.466667,16.322581,15.387097,11.433333,9.709677,...,8.033333,1.83871,4.290323,3.785714,3.741935,7.266667,11.612903,16.466667,16.483871,16.612903

In [58]:
tempdf.columns = dates
tempdf = tempdf.drop(tempdf.index[0])
tempdf2 = tempdf.reset_index()
tempdf2.rename(columns = {'index':'Country_Code'}, inplace = True)
tempdf2.head()

ValueError: Length mismatch: Expected axis has 22 elements, new values have 452 elements

In [7]:
tempdf2.to_csv("tempmeans.csv")